#!/bin/python3

import math
import os
import random
import re
import sys

# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path


def countingValleys(steps, path):
    current = 0        #initialize the position of the hiker
    valley = 0         #initialize the number of valley  
    for j in path:
        if j == 'U':
            if current == -1:
                valley += 1
            current += 1
        else:
                current -= 1
                
    return valley
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
